spring:
      datasource:
          url: jdbc:h2:mem:testdb
          driverClassName: org.h2.Driver
          username:master
          password:master
      jpa: 
          database-platform: org.hibernate.dialect.H2Dialect
      h2:
          console.enabled: true